export default {
    AUTH_REDUCER: 'AUTH_REDUCER',
    CURRENT_SONG_REDUCER: 'CURRENT_SONG_REDUCER',
    RECENT_SEARCHES_REDUCER: 'RECENT_SEARCHES_REDUCER',
    DYNAMIC_LINK_REDUCER: 'DYNAMIC_LINK_REDUCER'
}